apiVersion: v1 
kind: Service 
metadata:
  name: clahan-company-web
spec:
  selector:
    app: node-clahan-web
  ports:
    - port: 82
      targetPort: 3000
      protocol: TCP
  type: NodePort                    
