piVersion: v1 
kind: Service
metadata:
  name: clahan-company-web
spec:
  selector:
    app: clahan-web
  ports:
    - port: 82
      targetPort: 80
      protocol: TCP
  type: LoadBalancer     

       